# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbdokument
team: biff
replicas:
  min: 1
  max: 2
  cpuThresholdPercentage: 50
port: 8080
webproxy: true
healthcheck:
  liveness:
    path: veilarbdokument/internal/isAlive
    initialDelay: 90
  readiness:
    path: veilarbdokument/internal/isReady
    initialDelay: 90
prometheus:
  enabled: true
  path: veilarbdokument/internal/metrics
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
fasitResources:
  used:
    - alias: srvveilarbdokument
      resourceType: credential
    - alias: Dokumentproduksjon_v3
      resourceType: webserviceendpoint
    - alias: Aktoer_v2
      resourceType: webserviceendpoint
    - alias: securityTokenService
      resourceType: baseurl
    - alias: unleash-api
      resourceType: restservice
    - alias: appdynamics
      resourceType: applicationproperties

    - alias: isso-host
      resourceType: baseurl
    - alias: isso-rp-user
      resourceType: credential
    - alias: isso-jwks
      resourceType: baseurl
    - alias: isso-issuer
      resourceType: baseurl
    - alias: veilarblogin.redirect-url
      resourceType: restservice
      propertyMap:
        url: OIDC_REDIRECT_URL
    - alias: isso.isalive
      resourceType: baseurl
    - alias: sak.saker
      resourceType: restservice
      propertyMap:
        url: SAK_API_URL
    - alias: abac.pdp.endpoint
      resourceType: restservice
    - alias: veilarbarenaAPI
      resourceType: restservice

alertProfiles:
  - common-java-modules
